{% set name = "pferd" %}
{% set version = "3.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pferd-{{ version }}.tar.gz
  sha256: 3a17c63bd9e135bd725bc3eadb479739e3e2f8124887cc96f87e076d534bde28

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pferd = PFERD.__main__:main
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - aiohttp >=3.8.1
    - beautifulsoup4 >=4.10.0
    - rich >=11.0.0
    - keyring >=23.5.0
    - certifi >=2021.10.8

test:
  imports:
    - PFERD
  commands:
    - pip check
    - pferd --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pferd/
  summary: Programm zum Flotten Einfachen Runterladen von Dateien
  dev_url: https://github.com/Garmelon/PFERD
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
