{% set name = "pferd" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pferd-{{ version }}.tar.gz
  sha256: 4fce35cb61a75e99b0ba8aed3ffef98c84b4059f4c424f966c37fb6b73f83dd1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pferd = PFERD.__main__:main
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - aiohttp >=3.8.1
    - beautifulsoup4 >=4.10.0
    - rich >=11.0.0
    - keyring >=23.5.0
    - certifi >=2021.10.8

test:
  imports:
    - PFERD
  commands:
    - pip check
    - pferd --help
  requires:
    - pip

about:
  home: https://pypi.org/project/pferd/
  summary: Programm zum Flotten Einfachen Runterladen von Dateien
  dev_url: https://github.com/Garmelon/PFERD
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
